// Code generated by entc, DO NOT EDIT.

package warning

const (
	// Label holds the string label denoting the warning type in the database.
	Label = "warning"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldDate holds the string denoting the date field in the database.
	FieldDate = "date"

	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"

	// Table holds the table name of the warning in the database.
	Table = "warnings"
	// UserTable is the table the holds the user relation/edge.
	UserTable = "warnings"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "warning_user"
)

// Columns holds all SQL columns for warning fields.
var Columns = []string{
	FieldID,
	FieldReason,
	FieldDate,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Warning type.
var ForeignKeys = []string{
	"guild_warnings",
	"warning_user",
}
