// Code generated by entc, DO NOT EDIT.

package guild

const (
	// Label holds the string label denoting the guild type in the database.
	Label = "guild"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// EdgeWarnings holds the string denoting the warnings edge name in mutations.
	EdgeWarnings = "warnings"

	// Table holds the table name of the guild in the database.
	Table = "guilds"
	// WarningsTable is the table the holds the warnings relation/edge.
	WarningsTable = "warnings"
	// WarningsInverseTable is the table name for the Warning entity.
	// It exists in this package in order to avoid circular dependency with the "warning" package.
	WarningsInverseTable = "warnings"
	// WarningsColumn is the table column denoting the warnings relation/edge.
	WarningsColumn = "guild_warnings"
)

// Columns holds all SQL columns for guild fields.
var Columns = []string{
	FieldID,
}
