// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Guild is the predicate function for guild builders.
type Guild func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Warning is the predicate function for warning builders.
type Warning func(*sql.Selector)
